name: example_external
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  sqflite_annotation:
    path: ../sqflite_annotation
  sql_external_db:
    path: ../sql_external_db
  path_provider: ^2.1.4
  path: ^1.9.0
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_generator:
    path: ../sqflite_generator
flutter:
  uses-material-design: true